### ISSUE TITLE
[Documentation] Tutorial?

### ISSUE THREAD

**Issue by rubyFeedback** [Nornec/open-midinous#1]
Hey James,

First off great work on Midinous. I've always wanted to use ruby to autogenerate stuff, including music, but I lack knowledge in regards to audio, so that felt always a distant goal.

You added a video tutorial (I think), but I am actually looking for some explanation (that is, text) that could explain some parts of the code, in particular the ruby side, perhaps also the GUI part (but I guess the non-GUI part is more important).

I am not sure if you have enough time or motivation so pleae consider this just a very simple question - if for whatever the reason you can not do so, just ignore this. From a user perspective this is not needed, but more for other developers perhaps who are curious about the inner workings.

This does not have to be long, by the way! Perhaps 1-2 DIN A4 pages (not sure if you use european norms; for US norms DIN A4 equals roughly the US Letter format with 8.5 x 11 inches, aka 215.9 x 279.4 mm - sort of a full normal page for most oldschool paper ~notebooks). This is not urgent either, perhaps just within the next 18 months or so whenever you have some time.

What I am most interested in is the generative aspect e. g. how code can be used to produce music.

By the way, on a side note - do you know the contextfree design grammar, and the project?

An example of their gallery is here:

https://www.contextfreeart.org/gallery2/

This is not related to Midinous, and cfdg has a few problems (it's not so simple, IMO), but it sort of reminded me a bit here ... e. g. to autogenerate images ... or, autogenerate music, like in Midinous.

**Comment by Nornec** [comment]
I'd be happy to explain parts of the code. Were there areas/concepts/genres that you were interested in? If i start blabbering on about the inner workings i could probably go on for pages (and perhaps I should, for future viewers' sake).
I submit that the code is not commented well, that's a fault of a feedback loop of rapid development and instant gratification. Certainly I know how it works, but if I were me just starting out, I'd be completely lost.
If you could focus your question a bit more, I'll certainly try to approach the prompt pragmatically and give you something more worth your while. Feel free to browse the code and tell me places within that you are curious about (files, line numbers), and maybe we can go from there?

**Comment by Nornec** [comment]
Please request a re-open of this issue via email. Closing for now.
